name: campus_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (all null-safe and compatible with Dart 3)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  file_picker: ^10.3.6
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  dio: ^5.9.0
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  mime: ^2.0.0
  url_launcher: ^6.3.2
  open_file: ^3.5.10
  flutter_local_notifications: ^19.5.0
  shimmer: ^3.0.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/data/campus_data.json
    - assets/images/onboarding_1.jpg
    - assets/images/onboarding_2.jpg
    - assets/images/onboarding_3.jpg
    - assets/images/onboarding_4.jpg
    - assets/images/onboarding_5.jpg
